.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 2/5/16
.Dt unicornleap 1
.Os Darwin
.Sh NAME
.Nm unicornleap
.Nd display a flying unicorn
.Sh SYNOPSIS
.Nm
.Op Fl hv                \" [-hv]
.Op Fl s Ar seconds      \" [-a path]
.Op Fl n Ar number       \" [-a path]
.Op Fl u Ar unicorn      \" [-a path]
.Op Fl k Ar sparkle      \" [-a path]
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
makes a unicorn fly across your screen. That's all it does.
.Sh OPTIONS
.Bl -tag -width "-u, --unicorn filename "
.It Fl h , \-help
Display usage information.
.It Fl s , \-seconds Ar n
Animate for n seconds.
.br
Defaults to
.Ar 2.0
.It Fl n , \-number Ar i
Display i unicorns.
.br
Defaults to
.Ar 1
.It Fl u , \-unicorn Ar filename
Filename for unicorn image.
.br
Defaults to
.Ar ~/.unicornleap/unicorn.png
.It Fl s , \-sparkle Ar filename
Filename for sparkle image.
.br
Defaults to
.Ar ~/.unicornleap/sparkle.png
.It Fl v , \-verbose
Print verbose messages
.El                      \" Ends the list
.Pp
.Sh FILES                \" File used or created by the topic of the man page
.Bl -tag -width "~/.unicornleap/unicorn.png" -compact
.It Pa ~/.unicornleap/unicorn.png
The magic image. This must exist and be a valid PNG.
.It Pa ~/.unicornleap/sparkle.png
The image for the sparkle effect. This must exist and be a valid PNG.
.El                      \" Ends the list
