.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 3/5/13
.Dt unicornleap 1
.Os Darwin
.Sh NAME
.Nm unicornleap
.Nd display a flying unicorn
.Sh SYNOPSIS
.Nm
.Op Fl vh                \" [-vh]
.Op Fl s Ar seconds      \" [-a path]
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
makes a unicorn fly across your screen. That's all it does.
.Sh OPTIONS
.Bl -tag -width "-s, --seconds n "
.It Fl s , \-seconds Ar n
Number of seconds for the animation to last.
.br
Defaults to
.Ar 2.0
.It Fl n , \-number Ar n
Number of unicorns to display.
.br
Defaults to
.Ar 1
.It Fl h , \-help
Display help
.It Fl v
Slightly more output
.El                      \" Ends the list
.Pp
.Sh FILES                \" File used or created by the topic of the man page
.Bl -tag -width "~/.unicornleap/unicorn.png" -compact
.It Pa ~/.unicornleap/unicorn.png
The magic image. This must exist and be a valid PNG.
.It Pa ~/.unicornleap/sparkle.png
The image for the sparkle effect. This must exist and be a valid PNG.
.El                      \" Ends the list
